In [1]:
import torch
import torch.nn as nn

In [ ]:
# class Model(nn.Module):
#     def __init__(self, num_features):
#         super().__init__()
#         self.linear1 = nn.Linear(num_features, 3)                      # without sequential
#         self.relu = nn.ReLU()
#         self.linear2 = nn.Linear(3,1)
#         self.sigmoid = nn.Sigmoid()

#     def forward(self,features):
#         out = self.linear1(features)
#         out = self.relu(out)
#         out = self.linear2(out)
#         out = self.sigmoid(out)

#         return out        
    



class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )
        

    def forward(self,features):
        out = self.network(features)

        return out        

In [ ]:
 # create dataset
features = torch.rand(10,5)       

In [ ]:
model = Model(features.shape[1])     
model(features)  

tensor([[0.4510],
        [0.4314],
        [0.4441],
        [0.4503],
        [0.4329],
        [0.4442],
        [0.4510],
        [0.4619],
        [0.4259],
        [0.4404]], grad_fn=<SigmoidBackward0>)

In [32]:
model.network[0].weight

Parameter containing:
tensor([[-0.4268, -0.1552, -0.4107, -0.1856,  0.0768],
        [ 0.1464,  0.3718,  0.0976, -0.0684, -0.2946],
        [-0.2865,  0.3993, -0.3173,  0.1836, -0.1543]], requires_grad=True)

In [33]:
model.network[0].bias

Parameter containing:
tensor([ 0.0106,  0.4206, -0.1575], requires_grad=True)

In [34]:
from torchinfo import summary

summary(model, input_size = (10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00