In [1]:
import torch

print(torch.__version__)

/Users/rachin/Desktop/pytorch/torchVenv/lib/python3.10/site-packages/torch/_subclasses/functional_tensor.py:362: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


2.12.0


In [2]:
if torch.cuda.is_available():
    print("GPU is available")
    print("using GPU: ", torch.cuda.get_device_name(0))
else:
    print("GPU is not available, using CPU")

GPU is not available, using CPU


## Creating Tensors

In [3]:
a = torch.empty(2,3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [4]:
# check type
type(a)

torch.Tensor

In [5]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
#using ones 
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
# using rand
torch.rand(2,3)

tensor([[0.0238, 0.2406, 0.6631],
        [0.3187, 0.4167, 0.3994]])

In [8]:
# manual seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [9]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
# using tensors

torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
# otherway

# using arange
print("using arange ---->",torch.arange(0,10,2))

#using linespace
print("Using linespace ---->",torch.linspace(0,10,5))

#using eye
print("Using eye ---->",torch.eye(3))

#uisng full
print("using full ---->",torch.full((3,3), 7))

using arange ----> tensor([0, 2, 4, 6, 8])
Using linespace ----> tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
Using eye ----> tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
using full ----> tensor([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]])


## Tensor shape

In [12]:
x = torch.tensor([[1,2,3],[4,5,6]])

x.shape

torch.Size([2, 3])

In [13]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [14]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [15]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [16]:
torch.rand_like(x, dtype = torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## dtype

In [17]:
# find data type
x.dtype

torch.int64

In [18]:
# assign data type
torch.tensor([1.0, 2.0, 3.0], dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [19]:
torch.tensor([1,2,3], dtype = torch.float32)

tensor([1., 2., 3.])

In [20]:
# using "to" to change existing tensor data type

x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

## mathematical operation

In [21]:
## scale operation

x = torch.rand(2,3)
x

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

In [22]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.5066, 0.6203, 0.1750],
        [0.8125, 0.9938, 0.5723]])

In [23]:
## element wise operation

a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])
tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]])


In [24]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.2239, 0.3023, 0.1784],
        [0.3346, 0.0706, 0.2767]])

In [25]:
c = torch.tensor([-2,3,1,-4])

In [26]:
#abs
torch.abs(c)

tensor([2, 3, 1, 4])

In [27]:
#negative
torch.neg(c)

tensor([ 2, -3, -1,  4])

In [28]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [29]:
#round
torch.round(d)

tensor([2., 2., 4., 4.])

In [30]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [31]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [32]:
# clamp
torch.clamp(d, min = 2, max = 3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

## reduction operaton

In [33]:
c = torch.randint(size = (3,3), low = 0 , high = 10, dtype = torch.float32)
c

tensor([[7., 0., 0.],
        [9., 5., 7.],
        [3., 9., 4.]])

In [34]:
# sum
torch.sum(c)

#sum along columns
torch.sum(c, dim = 0)

# sum along rows 
torch.sum(c, dim = 1)

tensor([ 7., 21., 16.])

In [35]:
# mean
torch.mean(c)

#mean along column
torch.mean(c, dim = 0)


tensor([6.3333, 4.6667, 3.6667])

In [36]:
# median
torch.median(c)

tensor(5.)

In [37]:
torch.max(c)
torch.min(c)

tensor(0.)

In [38]:
# product
torch.prod(c)

tensor(0.)

In [39]:
# standard deviation
torch.std(c)

tensor(3.4440)

In [40]:
# variance
torch.var(c)

tensor(11.8611)

In [41]:
#argmax
torch.argmax(c)

tensor(3)

In [42]:
torch.argmin(c)

tensor(1)

## Matrix operations

In [43]:
x = torch.randint(size = (2,3), low = 0, high = 10)
y = torch.randint(size = (3,2), low = 0, high = 10)
print(x)
print(y)

tensor([[0, 5, 7],
        [5, 9, 9]])
tensor([[7, 5],
        [9, 8],
        [9, 7]])


In [44]:
# matrix multiplication

torch.matmul(x,y)

tensor([[108,  89],
        [197, 160]])

In [45]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

In [46]:
# dot product
torch.dot(vector1, vector2)

tensor(11)

In [47]:
# transpose
torch.transpose(x, 0, 1)

tensor([[0, 5],
        [5, 9],
        [7, 9]])

In [48]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[9., 2., 6.],
        [7., 7., 8.],
        [3., 6., 1.]])

In [49]:
# determinant
torch.det(h)

tensor(-209.)

In [50]:
# inverse
torch.inverse(h)

tensor([[ 0.1962, -0.1627,  0.1244],
        [-0.0813,  0.0431,  0.1435],
        [-0.1005,  0.2297, -0.2344]])

## comparison operation

In [51]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[5, 5, 0],
        [4, 3, 8]])
tensor([[8, 3, 3],
        [5, 0, 6]])


In [52]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

## special function

In [53]:
k = torch.randint(size=(2,3), low = 0 , high = 10, dtype = torch.float32)
k

tensor([[4., 0., 8.],
        [4., 7., 2.]])

In [54]:
# log
torch.log(k)

tensor([[1.3863,   -inf, 2.0794],
        [1.3863, 1.9459, 0.6931]])

In [55]:
# exp
torch.exp(k)

tensor([[5.4598e+01, 1.0000e+00, 2.9810e+03],
        [5.4598e+01, 1.0966e+03, 7.3891e+00]])

In [56]:
# sqrt
torch.sqrt(k)

tensor([[2.0000, 0.0000, 2.8284],
        [2.0000, 2.6458, 1.4142]])

In [57]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9820, 0.5000, 0.9997],
        [0.9820, 0.9991, 0.8808]])

In [58]:
# softmax
torch.softmax(k, dim=0)

tensor([[5.0000e-01, 9.1105e-04, 9.9753e-01],
        [5.0000e-01, 9.9909e-01, 2.4726e-03]])

In [59]:
# relu
torch.relu(k)

tensor([[4., 0., 8.],
        [4., 7., 2.]])

## inplace operation

In [60]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6868, 0.4920, 0.0748],
        [0.9605, 0.3271, 0.0103]])
tensor([[0.9516, 0.2855, 0.2324],
        [0.9141, 0.7668, 0.1659]])


In [ ]:
m.add_(n) ## n is added to m.no new memory is create

tensor([[1.6384, 0.7776, 0.3072],
        [1.8746, 1.0939, 0.1762]])

In [62]:
m

tensor([[1.6384, 0.7776, 0.3072],
        [1.8746, 1.0939, 0.1762]])

In [63]:
n


tensor([[0.9516, 0.2855, 0.2324],
        [0.9141, 0.7668, 0.1659]])

In [ ]:
torch.relu(m) #this will create different memory space

tensor([[1.6384, 0.7776, 0.3072],
        [1.8746, 1.0939, 0.1762]])

In [66]:
m.relu_() # this will happen in the same memory space as m

tensor([[1.6384, 0.7776, 0.3072],
        [1.8746, 1.0939, 0.1762]])

In [67]:
m

tensor([[1.6384, 0.7776, 0.3072],
        [1.8746, 1.0939, 0.1762]])

## copying tensors

In [68]:
a = torch.rand(2,3)
a

tensor([[0.4393, 0.2243, 0.8935],
        [0.0497, 0.1780, 0.3011]])

In [69]:
b = a

In [70]:
b

tensor([[0.4393, 0.2243, 0.8935],
        [0.0497, 0.1780, 0.3011]])

In [71]:
a[0][0]= 0

In [72]:
a

tensor([[0.0000, 0.2243, 0.8935],
        [0.0497, 0.1780, 0.3011]])

In [73]:
b

tensor([[0.0000, 0.2243, 0.8935],
        [0.0497, 0.1780, 0.3011]])

In [74]:
id(a)

4505452304

In [75]:
id(b)

4505452304

In [76]:
b = a.clone()

In [77]:
a

tensor([[0.0000, 0.2243, 0.8935],
        [0.0497, 0.1780, 0.3011]])

In [78]:
b

tensor([[0.0000, 0.2243, 0.8935],
        [0.0497, 0.1780, 0.3011]])

In [79]:
a[0][0] = 1

In [80]:
a

tensor([[1.0000, 0.2243, 0.8935],
        [0.0497, 0.1780, 0.3011]])

In [81]:
b

tensor([[0.0000, 0.2243, 0.8935],
        [0.0497, 0.1780, 0.3011]])

In [82]:
id(a)

4505452304

In [83]:
id(b)

4505197344